import Image from "next/image";
import styles from "../styles/Home.module.css";
import "../styles/globals.css";
import Banner from "../../public/assets/banner.png";
import Banner2 from "../../public/assets/banner4.jpg";
import { useState } from "react";
import { filtrarProdutos, buscarProduto, produtosEntradas } from "../service";
import Head from "next/head";
import Cards from "../components/Cards";
import Categorias from "../components/Categorias";
import CampoDeBusca from "../components/CampoDeBusca";
import BotaoDarkMode from "@/components/BotaoDarkMode";
import { produtos } from "../data/data-produtos.js";

export default function Home() {
	const [dadosFiltrados, setDadosFiltrados] = useState(produtosEntradas);
	const [textoBuscaDigitado, setTextoBuscaDigitado] = useState("");
	const [botaoClicado, setBotaoClicado] = useState("Entradas");
	const [darkMode, setDarkMode] = useState(false);

	const handleBusca = (textoDigitado) => {
		setTextoBuscaDigitado(textoDigitado);
		textoDigitado.length >= 4 && setDadosFiltrados(buscarProduto(textoDigitado));
		setBotaoClicado("");
	};

	const handleFiltro = (categoria) => {
		setTextoBuscaDigitado("");
		setDadosFiltrados(filtrarProdutos(categoria));
		setBotaoClicado(categoria);
	};

	const toggleDarkMode = () => {
		setDarkMode(!darkMode);
	};

	return (
		<>
			<Head>
				<title>RESTAURANT</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
				<link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Poppins&display=swap" rel="stylesheet" />
			</Head>
			<div className={`${darkMode ? styles.darkMode : ""}`}>
				<header className={styles.banner}>
					<Image src={Banner2} alt="banner" />
					<div>
						<h1>RESTAURANT</h1>
						<p>
							From classic dishes to surprising creations,
							<br />
							our menu is a refinement of organic flavors.
						</p>
					</div>
				</header>

				<main className={`${styles.container_principal} ${darkMode ? styles.darkMode : ""}`}>
					<Categorias handleFiltro={handleFiltro} botaoClicado={botaoClicado} darkModearkMode={darkMode} />

					<CampoDeBusca textoBuscaDigitado={textoBuscaDigitado} handleBusca={handleBusca} />

					<section className={`${styles.secao_cards}`}>
						<div>
							<h2>Menu</h2>
							<BotaoDarkMode toggleDarkMode={toggleDarkMode} darkMode={darkMode} />
						</div>

						<div className={styles.container_cards}>
							{dadosFiltrados.map((produto) => (
								<Cards key={produto.id} produto={produto} />
							))}
						</div>
					</section>
				</main>
			</div>
		</>
	);
}
